package com.beans;
// Generated Feb 18, 2013 11:37:54 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * PatientInside generated by hbm2java
 */
public class PatientInside  implements java.io.Serializable {


     private int admisionId;
     private int patientId;
     private int doctorId;
     private int bedId;
     private String admisionDate;

    public PatientInside() {
    }

    public PatientInside(int admisionId, int patientId, int doctorId, int bedId, String admisionDate) {
       this.admisionId=admisionId;
    	this.patientId = patientId;
       this.doctorId = doctorId;
       this.bedId = bedId;
       this.admisionDate = admisionDate;
    }
   
    public int getAdmisionId() {
        return this.admisionId;
    }
    
    public void setAdmisionId(int admisionId) {
        this.admisionId = admisionId;
    }
    public int getPatientId() {
        return this.patientId;
    }
    
    public void setPatientId(int patientId) {
        this.patientId = patientId;
    }
    public int getDoctorId() {
        return this.doctorId;
    }
    
    public void setDoctorId(int doctorId) {
        this.doctorId = doctorId;
    }
    public int getBedId() {
        return this.bedId;
    }
    
    public void setBedId(int bedId) {
        this.bedId = bedId;
    }
    public String getAdmisionDate() {
        return this.admisionDate;
    }
    
    public void setAdmisionDate(String admisionDate) {
        this.admisionDate = admisionDate;
    }




}


