package com.beans;
// Generated Feb 18, 2013 11:37:54 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Patient generated by hbm2java
 */
public class Patient  implements java.io.Serializable {




	private int patientRegistrationno;
     private String patientName;
     private String patientGender;
     private String patientAge;
     private String patientMaritalStatus;
     private String patientFatherHusband;
     private String patientAddress;
     private String patientCity;
     private String patientReligion;
     private String patientMobile;
     private String patientTelephone;
     private String patientBloodgroup;
     private String patientDisease;
     private String patientDateofregistraton;

    public Patient() {
    }

    public Patient(int patientRegistrationno, String patientName,
			String patientGender, String patientAge,
			String patientMaritalStatus, String patientFatherHusband,
			String patientAddress, String patientCity, String patientReligion,
			String patientMobile, String patientTelephone,
			String patientBloodgroup, String patientDisease,
			String patientDateofregistraton) {

		this.patientRegistrationno = patientRegistrationno;
		this.patientName = patientName;
		this.patientGender = patientGender;
		this.patientAge = patientAge;
		this.patientMaritalStatus = patientMaritalStatus;
		this.patientFatherHusband = patientFatherHusband;
		this.patientAddress = patientAddress;
		this.patientCity = patientCity;
		this.patientReligion = patientReligion;
		this.patientMobile = patientMobile;
		this.patientTelephone = patientTelephone;
		this.patientBloodgroup = patientBloodgroup;
		this.patientDisease = patientDisease;
		this.patientDateofregistraton = patientDateofregistraton;
	}
   
    public Integer getPatientRegistrationno() {
        return this.patientRegistrationno;
    }
    
    public void setPatientRegistrationno(Integer patientRegistrationno) {
        this.patientRegistrationno = patientRegistrationno;
    }
    public String getPatientName() {
        return this.patientName;
    }
    
    public void setPatientName(String patientName) {
        this.patientName = patientName;
    }
    public String getPatientAge() {
        return this.patientAge;
    }
    
    public void setPatientAge(String patientAge) {
        this.patientAge = patientAge;
    }
    public String getPatientAddress() {
        return this.patientAddress;
    }
    
    public void setPatientAddress(String patientAddress) {
        this.patientAddress = patientAddress;
    }
    public String getPatientCity() {
        return this.patientCity;
    }
    
    public void setPatientCity(String patientCity) {
        this.patientCity = patientCity;
    }
    public String getPatientReligion() {
        return this.patientReligion;
    }
    
    public void setPatientReligion(String patientReligion) {
        this.patientReligion = patientReligion;
    }
    public String getPatientMobile() {
        return this.patientMobile;
    }
    
    public void setPatientMobile(String patientMobile) {
        this.patientMobile = patientMobile;
    }
    public String getPatientTelephone() {
        return this.patientTelephone;
    }
    
    public void setPatientTelephone(String patientTelephone) {
        this.patientTelephone = patientTelephone;
    }
    public String getPatientBloodgroup() {
        return this.patientBloodgroup;
    }
    
    public void setPatientBloodgroup(String patientBloodgroup) {
        this.patientBloodgroup = patientBloodgroup;
    }
    public String getPatientDisease() {
        return this.patientDisease;
    }
    
    public void setPatientDisease(String patientDisease) {
        this.patientDisease = patientDisease;
    }
    public String getPatientDateofregistraton() {
        return this.patientDateofregistraton;
    }
    
    public void setPatientDateofregistraton(String patientDateofregistraton) {
        this.patientDateofregistraton = patientDateofregistraton;
    }

	public void setPatientRegistrationno(int patientRegistrationno) {
		this.patientRegistrationno = patientRegistrationno;
	}


	public String getPatientGender() {
		return patientGender;
	}


	public void setPatientGender(String patientGender) {
		this.patientGender = patientGender;
	}


	public String getPatientMaritalStatus() {
		return patientMaritalStatus;
	}


	public void setPatientMaritalStatus(String patientMaritalStatus) {
		this.patientMaritalStatus = patientMaritalStatus;
	}


	public String getPatientFatherHusband() {
		return patientFatherHusband;
	}


	public void setPatientFatherHusband(String patientFatherHusband) {
		this.patientFatherHusband = patientFatherHusband;
	}




}


