package com.expenditure;
// Generated Feb 20, 2013 10:16:51 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Expenditure generated by hbm2java
 */
public class Expenditure_Beans  implements java.io.Serializable {


     private int EId;
     private String EItem;
     private String EDate;
     private String ECost;
     private String ERemark;

    public Expenditure_Beans() {
    }

    public Expenditure_Beans(int EId,String EItem, String EDate, String ECost, String ERemark) {
       
    	this.EId=EId;
    	this.EItem = EItem;
       this.EDate = EDate;
       this.ECost = ECost;
       this.ERemark = ERemark;
    }
   
    public int getEId() {
        return this.EId;
    }
    
    public void setEId(int EId) {
        this.EId = EId;
    }
    public String getEItem() {
        return this.EItem;
    }
    
    public void setEItem(String EItem) {
        this.EItem = EItem;
    }
    public String getEDate() {
        return this.EDate;
    }
    
    public void setEDate(String EDate) {
        this.EDate = EDate;
    }
    public String getECost() {
        return this.ECost;
    }
    
    public void setECost(String ECost) {
        this.ECost = ECost;
    }
    public String getERemark() {
        return this.ERemark;
    }
    
    public void setERemark(String ERemark) {
        this.ERemark = ERemark;
    }




}


